"""Versioned contracts shared by the core, adapters and simulations."""

from .models import (
    BoundingBox,
    CaptureRequest,
    CaptureResult,
    CaptureStatus,
    MediaAsset,
    PersonDetection,
    RiderAssignment,
    RiderAssignmentStatus,
    TagObservation,
    TagAssignmentEvidence,
    TagRegistryEntry,
    StorageReceipt,
    Vector3,
)
from .scenario import (
    GeneratedScenarioSource,
    ScenarioDefinition,
    ScenarioComponents,
    ScenarioDetector,
    ScenarioExpectation,
    ScenarioFaults,
    ScenarioVideo,
    SyntheticBearTagSample,
    SyntheticBearTagSeries,
    SyntheticMotionWindow,
    TimelineEvent,
    load_scenario,
)

__all__ = [
    "BoundingBox",
    "CaptureRequest",
    "CaptureResult",
    "CaptureStatus",
    "GeneratedScenarioSource",
    "MediaAsset",
    "PersonDetection",
    "RiderAssignment",
    "RiderAssignmentStatus",
    "ScenarioDefinition",
    "ScenarioComponents",
    "ScenarioDetector",
    "ScenarioExpectation",
    "ScenarioFaults",
    "ScenarioVideo",
    "SyntheticBearTagSample",
    "TagObservation",
    "TagAssignmentEvidence",
    "TagRegistryEntry",
    "StorageReceipt",
    "TimelineEvent",
    "SyntheticBearTagSeries",
    "SyntheticMotionWindow",
    "Vector3",
    "load_scenario",
]
