# Edge Application Configuration
# BearVision Edge Device YAML Configuration File
#
# This file contains the essential parameters for the edge application.
# All parameters have sensible defaults that work out-of-the-box.

# Recording Settings
recording:
  post_detection_duration: 5.0    # Active recording duration AFTER wakeboarder detection (in seconds)
                                   # Total clip length = 15s hindsight + post_detection_duration
  hindsight_enabled: true          # Enable GoPro Hindsight mode for 15-second pre-recording buffer

# YOLO Detection Settings
detection:
  yolo_enabled: true                  # Enable/disable person detection
  yolo_model: "yolov8n"               # Model size: yolov8n (nano), yolov8s (small), yolov8m (medium), yolov8l (large), yolov8x (xlarge)
  confidence_threshold: 0.5           # Minimum confidence for valid detection (0.0-1.0)
  cooldown: 2.0                       # Minimum seconds between consecutive detections

# Stream Performance Settings
performance:
  stream_max_fps: 30                  # Frame processing rate (1-120 fps)
  stream_max_lag_ms: 250              # Maximum acceptable lag in milliseconds before dropping frames

# Error Recovery Settings
error_recovery:
  max_restarts: 5                     # Maximum number of automatic restart attempts on error
  restart_delay: 2.0                  # Delay in seconds before attempting restart after error

# Background Thread Settings
threads:
  enable_ble_logging: true            # Enable BLE beacon logging thread
  enable_cloud_upload: false           # Enable cloud upload thread

# System Settings
system:
  log_level: "DEBUG"                   # Logging level: DEBUG, INFO, WARNING, ERROR
