videos:
  - path/to/video1.mp4
detection_gap_timeout_s: 3.0
sampling:
  fps: 5.0
  min_person_bbox_diagonal_ratio: 0.001
quality:
  blur: 1.0
  luma_min: 1
  luma_max: 20000
yolo:
  weights: yolov8s.onnx
  conf_thr: 0.20
trajectory:
  cutoff_hz: 0.1
export:
  output_dir: dataset
  format: cvat
gui:
  preview_width: 280
  preview_panel_width: 300
  preview_image_min_height: 200
  trajectory_image_min_height: 150
