videos:
  - path/to/video1.mp4
detection_gap_timeout_s: 2.0
sampling:
  fps: 5.0
  min_person_bbox_diagonal_ratio: 0.001
quality:
  blur: 1.0
  luma_min: 1
  luma_max: 20000
yolo:
  weights: yolov8s.onnx
  conf_thr: 0.20
trajectory:
  cutoff_hz: 1
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(funcName)s:%(lineno)d - %(message)s"
  debug_filename: "debug.log"
export:
  output_dir: dataset
  format: cvat
gui:
  preview_width: 350
  preview_panel_width: 400
  preview_image_min_height: 200
  trajectory_image_min_height: 200
  default_video_path: tests/data/TestMovie5_two_persons.mp4
  default_output_dir: tests/data/Test_2_riders
