"""Public component boundaries for BearVision 3."""

from .errors import (
    ComponentError,
    ComponentTimeout,
    ComponentUnavailable,
    InvalidComponentData,
    PermanentComponentError,
)
from .models import (
    CapturedClip,
    CapturedMedia,
    CaptureWindow,
    CaptureWindowBasis,
    CaptureWindowPrecision,
    ExtractedClip,
    PreparedClip,
    ProcessingTraceEvent,
    VideoFrame,
    requested_capture_window,
)
from .protocols import (
    Camera,
    ClipProcessor,
    Clock,
    Detector,
    FrameSource,
    JobQueue,
    ManagedJobQueue,
    MediaProbe,
    Storage,
    TagRegistry,
    TagScanner,
    VideoClipper,
)

__all__ = [
    "Camera",
    "CapturedClip",
    "CapturedMedia",
    "CaptureWindow",
    "CaptureWindowBasis",
    "CaptureWindowPrecision",
    "ClipProcessor",
    "Clock",
    "ComponentError",
    "ComponentTimeout",
    "ComponentUnavailable",
    "Detector",
    "ExtractedClip",
    "FrameSource",
    "InvalidComponentData",
    "JobQueue",
    "ManagedJobQueue",
    "MediaProbe",
    "PermanentComponentError",
    "PreparedClip",
    "ProcessingTraceEvent",
    "Storage",
    "TagRegistry",
    "TagScanner",
    "VideoFrame",
    "VideoClipper",
    "requested_capture_window",
]
